# Generated by Django 6.0.3 on 2026-03-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_chatmessage_recipient_alter_chatmessage_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="recipient",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("dermatologist", "Dermatologist"),
                    ("partnership", "Partnership"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
