# Generated by Django 6.0.3 on 2026-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0006_chatmessage_recipient_alter_chatmessage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nmc_certificate",
            field=models.ImageField(
                blank=True, null=True, upload_to="dermatologist_docs/nmc/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pan_card",
            field=models.ImageField(
                blank=True, null=True, upload_to="dermatologist_docs/pan/"
            ),
        ),
    ]
