# Generated by Django 6.0.3 on 2026-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0007_userprofile_nmc_certificate_userprofile_pan_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("dermatologist", "Dermatologist"),
                    ("partner", "Partner"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
