# Generated by Django 6.0.3 on 2026-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0008_userprofile_verification_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershiprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
