# Generated by Django 6.0.3 on 2026-03-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0009_partnershiprequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="partner_pan_card",
            field=models.ImageField(
                blank=True, null=True, upload_to="partner_docs/pan/"
            ),
        ),
    ]
