# Generated by Django 6.0.3 on 2026-03-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0011_skincareroutine"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershiprequest",
            name="product_picture",
            field=models.FileField(
                blank=True, null=True, upload_to="partnership_products/"
            ),
        ),
    ]
